import os
import logging
from sqlalchemy.orm import Session
from langchain_openai import ChatOpenAI
from langchain_core.prompts import ChatPromptTemplate
from langchain_core.output_parsers import JsonOutputParser
from models.budget_plans import BudgetPlan
from schemas.planning import BudgetPlanCreate
from typing import List, Dict, Any
from decimal import Decimal

# Setup logging
logger = logging.getLogger(__name__)

class PlanningService:
    def __init__(self):
        # Defaulting to GPT-4o for high-reasoning tasks like financial planning.
        # Ensure OPENAI_API_KEY is set in your .env file.
        self.llm = ChatOpenAI(model="gpt-4o", temperature=0.2)
        # We expect a list of plans (Conservative, Balanced, Aggressive)
        self.parser = JsonOutputParser()

    def generate_budget_plans(self, db: Session, user_id: str, month: str) -> List[dict]:
        """
        Generates three budget scenarios based on previous month's insights.
        """
        # 1. Fetch Insights (Placeholder: In production, retrieve data from Song Mingzheng's 'insights_reports' table)
        # Example logic: last_report = db.query(InsightReport).filter_by(user_id=user_id).first()
        # 需要从数据库获取数据，大概需要对获取到的数据进行整理，要争对uid进行获取最新的报告
        # 需要和分类的类名对齐
        context_data = (    # 测试数据
            "Last month total expenditure: 3,000 SGD. "
            "Breakdown: Dining 1,200 SGD (Overspent), Housing 1,000 SGD (Fixed), "
            "Transport 300 SGD, Entertainment 500 SGD."
        )

        # 2. Construct the Prompt with strict English constraints
        prompt = ChatPromptTemplate.from_template("""
            You are a professional Financial Planning Agent. Based on the user's spending context, 
            generate three distinct monthly budget scenarios for the upcoming month.
            
            User Context: {context}
            
            Requirements:
            1. Principle: Strictly follow the 50/30/20 rule (50% Needs, 30% Wants, 20% Savings).
            2. Scenarios: Provide exactly three scenarios: 'conservative' (max savings), 
               'balanced' (standard 50/30/20), and 'aggressive' (higher allowance for 'wants' while maintaining core savings).
            3. Currency: All values must be in SGD.
            4. Categories: Use standardized categories: 'Dining', 'Housing', 'Transport', 'Entertainment', 'Others'.
            5. Evidence: For each scenario, provide a brief English explanation of why the limits were set.
            
            {format_instructions}
        """)

        # 3. Execution Chain
        chain = prompt | self.llm | self.parser
        
        try:
            # Generate the plans via LLM
            plans = chain.invoke({
                "context": context_data,
                "format_instructions": self.parser.get_format_instructions()
            })
            
            # 4. Persistence (Optional: Save to DB here or in the API layer)
            # For each plan in plans: 
            #    new_entry = BudgetPlan(**plan, user_id=user_id, plan_month=month)
            #    db.add(new_entry)
            # db.commit()
            
            return self._validate_and_save(db, user_id, month, plans)
        except Exception as e:
            logger.error(f"Failed to generate budget plans: {str(e)}")
            return []
        
    def _validate_and_save(self, db: Session, user_id: str, month: str, raw_plans: List[Dict[str, Any]]) -> List[BudgetPlan]: 
        """
        Validates raw dicts against Pydantic schema and saves to PostgreSQL.
        """
        # 验证返回的数据是否符合格式，然后放入数据库
        db_objects = []
        
        for plan_dict in raw_plans:
            try:
                # Inject necessary metadata not generated by LLM
                plan_dict.update({
                    "user_id": user_id,
                    "plan_month": month
                })

                # STEP 1: Pydantic Validation
                # This ensures types match and no extra/missing fields exist
                validated_data = BudgetPlanCreate(**plan_dict)

                # STEP 2: Convert Pydantic to SQLAlchemy Model
                # .model_dump() is for Pydantic v2; use .dict() for v1
                db_plan = BudgetPlan(**validated_data.model_dump())
                
                db.add(db_plan)
                db_objects.append(db_plan)

            except Exception as val_err:
                logger.warning(f"Validation failed for a specific scenario: {val_err}")
                continue

        # STEP 3: Commit all valid scenarios at once (Atomic Transaction)
        if db_objects:
            try:
                db.commit()
                for obj in db_objects:
                    db.refresh(obj)
                logger.info(f"Successfully persisted {len(db_objects)} scenarios to Neon DB.")
            except Exception as db_err:
                db.rollback()
                logger.error(f"Database commit failed: {db_err}")
                return []

        return db_objects