name: Security Scan

on:
  push:
    branches: [ "main", "dev" ]
  pull_request:
    branches: [ "main" ]

jobs:
  vulnerability-scan:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      # 步骤 A：扫描文件系统中的第三方库依赖漏洞 (Python/JS)
      - name: Run Trivy vulnerability scanner (FS mode)
        uses: aquasecurity/trivy-action@master
        with:
          scan-type: 'fs'
          scan-ref: '.'
          exit-code: '1' # 如果发现漏洞，则让流水线失败
          severity: 'CRITICAL,HIGH'
          format: 'table'

      # - name: Build Docker Image
      #   run: docker build -t smart-spend-backend:latest .
      
      # - name: Run Trivy scanner (Image mode)
      #   uses: aquasecurity/trivy-action@master
      #   with:
      #     image-ref: 'smart-spend-backend:latest'
      #     severity: 'CRITICAL,HIGH'
